server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每5s发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10s不发送就过期

onlinemall:
  jwt:
    secret: onlinemall@Login(Auth}*^31)&szh% #登录校验的密钥
    pubKeyPath: C:\my\Code\projects\WebProjects\308shop\resources\rsa\rsa.pub # 公钥地址
    priKeyPath: C:\my\Code\projects\WebProjects\308shop\resources\rsa\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: OM_TOKEN
    coockieMaxAge: 30