server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    username: onlinemall
    password: root
    virtual-host: /onlinemall

onlinemall:
  sms:
    accessKeyId: LTAI4G3stW9Ms4k79UmxZ5SP # 你自己的accessKeyId
    accessKeySecret: PGn9gBXErw9XlpjjGFAVgQJZTIyESn # 你自己的AccessKeySecret
    signName: 308网上商城 # 签名名称
    verifyCodeTemplate: SMS_189622596 # 模板名称