server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/onlinemall?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: 192.168.1.104
    timeout: 5000ms
  rabbitmq:
    host: 127.0.0.1
    username: onlinemall
    password: root
    virtual-host: /onlinemall
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.onlinemall.user.mapper